server:
  port: 8080
spring:
  application:
    name: gateWay
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.147:8848
    gateway:
      server:
        webflux:
          routes:
            - id: userLogin
              uri: lb://userService
              predicates:
                - Path=/api/userLogin,/api/adminLogin,/api/logout,/api/toUserMain,/api/toAdminMain
            - id: memberService
              uri: lb://memberService
              predicates:
                - Path=/api/member/**
            - id: employeeService
              uri: lb://employeeService
              predicates:
                - Path=/api/employee/**
            - id: equipmentService
              uri: lb://equipmentService
              predicates:
                - Path=/api/equipment/**
            - id: userService
              uri: lb://userService
              predicates:
                - Path=/api/user/**